// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return web; // Android için aynı proje config
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-TSh2OFTSk7DuhBqh02897S9WGRNfzE',
    appId: '1:762121478248:web:bd76fd7951f39a885cdbdd',
    messagingSenderId: '762121478248',
    projectId: 'temiz-dunya',
    authDomain: 'temiz-dunya.firebaseapp.com',
    storageBucket: 'temiz-dunya.firebasestorage.app',
    measurementId: 'G-ES0TQF737R',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo-TSh2OFTSk7DuhBqh02897S9WGRNfzE',
    appId: '1:762121478248:web:bd76fd7951f39a885cdbdd',
    messagingSenderId: '762121478248',
    projectId: 'temiz-dunya',
    authDomain: 'temiz-dunya.firebaseapp.com',
    storageBucket: 'temiz-dunya.firebasestorage.app',
    measurementId: 'G-ES0TQF737R',
  );
}
